apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: ianmward/istio-fleetman-position-tracker:6
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        command: ["java","-Xmx50m","-jar","webapp.jar"]
        imagePullPolicy: Always